#!/bin/bash
# https://websiteforstudents.com/installing-php-7-0-7-1-ubuntu-17-04/

echo "Installing PHP 7.0 and packages."
sudo apt-get -y update
sudo apt-get install -y php php-fpm php-cli php-common php-mbstring php-gd php-intl php-xml php-mysql php-mcrypt php-zip php-json php-opcache php-readline php-curl
php -v