#!/bin/bash
# https://nodejs.org/en/download/package-manager/

echo "Instalando o Node.js + NPM."
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt-get install -y build-essential
npm -v
node -v