#!/bin/bash
echo "\nUninstall old versions:\n"
sudo apt-get remove docker docker-engine docker.io

echo "\nUpdate the apt package index:\n"
sudo apt-get -y update

echo "\nAllow Docker to use the aufs storage drivers:\n"
sudo apt-get install -y \
    linux-image-extra-$(uname -r) \
    linux-image-extra-virtual

echo "\nUpdate the apt package index:\n"
sudo apt-get -y update

echo "\nInstall packages to allow apt to use a repository over HTTPS:\n"
sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common

echo "\nAdd Docker’s official GPG key:\n"
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

echo "\nVerify that you now have the key with the fingerprint:\n9DC8 5822 9FC7 DD38 854A E2D8 8D81 803C 0EBF CD88\n"
sudo apt-key fingerprint 0EBFCD88

echo "\nSet up the stable repository:\n"
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

echo "\nUpdate the apt package index:\n"
sudo apt-get -y update

echo "\nInstall the latest version of Docker CE:\n"
sudo apt-get install docker-ce

echo "\nVerify that Docker CE is installed correctly:\n"
sudo docker run hello-world

sudo groupadd docker

sudo usermod -aG docker $USER