#!/bin/bash
# https://laravel-news.com/valet-for-ubuntu-linux
# https://cpriego.github.io/valet-linux/
echo "Installing Valet."
sudo apt-get install -y network-manager libnss3-tools jq xsel
composer global require cpriego/valet-linux
valet install
valet -v