#!/bin/bash

echo "Installing Laravel."
composer global require "laravel/installer"
echo '
# Laravel
export PATH="$HOME/.config/composer/vendor/bin:$PATH"' >> ~/.zshrc

echo "Done, close and open your terminal to use laravel command globaly."